package Exceptiondemo;
public class Trycatchdemo {
    public static void main(String[] args) {
        int val1=0,val2=25;
        int val3;
        try {
              val3=val2/val1;
              System.out.println(val3);
             } catch (ArithmeticException e) {
            System.out.println("Please Enter the value :: > 0 ");
            System.out.println("Hello Friends");
            System.out.println("FUEL Pune");
            System.out.println("Name;- Dipak Lodwal ");
    }
  
    
}
    
    
}
